name: Main Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1

    - name: Install NPM packages
      run: npm install
      working-directory: ./src

    - name: Restore NuGet packages
      run: dotnet restore --locked-mode

    - name: Generate *.cshtml.cs files
      run: dotnet build ./src/Hangfire.Dashboard.Management.v2.csproj --configuration Release -target:GenerateRazorClasses -p:PkgRazorGenerator_MsBuild="$NUGET_PACKAGES\razorgenerator.msbuild\2.5.0"

    - name: Build Project
      run: dotnet build ./src/Hangfire.Dashboard.Management.v2.csproj --configuration Release

    - name: Publish nuget
      run: dotnet nuget push **/*.nupkg
            --api-key ${{ secrets.NUGET_API_KEY }}
            --source https://api.nuget.org/v3/index.json
            --no-symbols
            --skip-duplicate
